#!/usr/bin/env python3
"""
GHOSTPORT - CARA CEK PROYEK
Panduan lengkap testing proyek
"""

print("=" * 80)
print("📋 GHOSTPORT - PANDUAN CEK PROYEK")
print("=" * 80)
print()

print("🔍 STEP 1: CEK FILE STRUCTURE")
print("-" * 80)
print("Jalankan:")
print("  python check_project.py")
print()
print("Output yang diharapkan:")
print("  ✅ PROJECT INTEGRITY: GOOD")
print("  ✅ All module files present and non-empty!")
print()

print("🔍 STEP 2: CEK COMPILATION (Tanpa Build Penuh)")
print("-" * 80)
print("Jalankan:")
print("  cargo check")
print()
print("Ini akan:")
print("  • Check syntax errors")
print("  • Check type errors")
print("  • Check missing imports")
print("  • TIDAK build binary (lebih cepat)")
print()
print("Output yang diharapkan:")
print("  Checking ghostport v3.0.0")
print("  Compiling ghostport v3.0.0")
print("  Finished dev [unoptimized + debuginfo] target(s) in X.XXs")
print()

print("🔨 STEP 3: BUILD PROJECT (Compile Penuh)")
print("-" * 80)
print("Jalankan:")
print("  cargo build --release")
print()
print("Ini akan:")
print("  • Compile semua file")
print("  • Optimize code (--release)")
print("  • Generate binary executable")
print()
print("Output yang diharapkan:")
print("  Compiling ghostport v3.0.0")
print("  Finished release [optimized] target(s) in XX.XXs")
print()
print("Binary location:")
print("  target/release/ghostport.exe (Windows)")
print("  target/release/ghostport (Linux/Mac)")
print()

print("🧪 STEP 4: TEST RUNNING")
print("-" * 80)
print("Test 1 - Help Menu:")
print("  .\\target\\release\\ghostport.exe --help")
print()
print("Test 2 - Version:")
print("  .\\target\\release\\ghostport.exe --version")
print()
print("Test 3 - List Plugins:")
print("  .\\target\\release\\ghostport.exe plugins")
print()
print("Test 4 - Quick Scan (Local):")
print("  .\\target\\release\\ghostport.exe scan -i 127.0.0.1 -e 100")
print()
print("Test 5 - Scan dengan Banner:")
print("  .\\target\\release\\ghostport.exe scan -i google.com -e 100 -b")
print()
print("Test 6 - Stealth Mode:")
print("  .\\target\\release\\ghostport.exe scan -i scanme.nmap.org -e 1000 --mode stealth")
print()

print("📊 STEP 5: CEK OUTPUT")
print("-" * 80)
print("Output scan yang benar harus menampilkan:")
print("  ╔══════════════════════════════════════════════════════════════╗")
print("  ║  GhostPort v3.0.0                                            ║")
print("  ║  Silent Network Recon Toolkit                                ║")
print("  ║  🕵️ Modular Stealth Reconnaissance Framework                 ║")
print("  ╚══════════════════════════════════════════════════════════════╝")
print()
print("  [*] Target: google.com (142.250.xxx.xxx)")
print("  [*] Ports: 1-100 (100 ports)")
print("  [*] Mode: ⚖️ Balanced speed and stealth")
print("  ...")
print("  [OPEN] xxx.xxx.xxx.xxx:80 → HTTP 🌐 Web")
print("  [OPEN] xxx.xxx.xxx.xxx:443 → HTTPS 🌐 Web")
print()

print("=" * 80)
print("🚨 JIKA ADA ERROR")
print("=" * 80)
print()
print("Error Common #1: Missing dependency")
print("  error: failed to fetch...")
print("  FIX: cargo update")
print()
print("Error Common #2: Cannot find in scope")
print("  error: cannot find type `ScanConfig` in this scope")
print("  FIX: Check config.rs - struct mungkin belum lengkap")
print()
print("Error Common #3: Type mismatch")
print("  error: mismatched types")
print("  FIX: Check import statements - pastikan semua menggunakan struct yang sama")
print()
print("Error Common #4: Brace mismatch")
print("  error: this file contains an unclosed delimiter")
print("  FIX: Check main.rs - mungkin ada { } yang tidak balance")
print()

print("=" * 80)
print("💡 TIPS")
print("=" * 80)
print("1. Gunakan 'cargo check' terlebih dahulu (lebih cepat)")
print("2. Jika 'cargo check' sukses, baru 'cargo build --release'")
print("3. Jika ada error, copy-paste error message untuk dianalisa")
print("4. Test dengan target aman dulu: 127.0.0.1 atau scanme.nmap.org")
print("5. Jangan scan sembarang IP tanpa izin!")
print()

print("=" * 80)
print("📝 CHECKLIST")
print("=" * 80)
print("[ ] File structure OK (python check_project.py)")
print("[ ] Cargo check passed")
print("[ ] Cargo build --release passed")
print("[ ] --help works")
print("[ ] plugins command works")
print("[ ] scan command works")
print("[ ] Output formatted correctly")
print()

print("✅ Jika semua checklist OK, project siap digunakan!")
print("=" * 80)
